/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ciber;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.io.IOException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author Jesus
 */
public class InterfazUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InterfazUsuario
     */

    HTMLEditorKit kit = new HTMLEditorKit();
    Dimension screenSize = null;
    boolean usando = false;
    JFrame principal = null;
    Cliente cliente = new Cliente(this);
    boolean continuarServicio;
    //boolean notificado = false;
    CheKConexion ping = new CheKConexion();
    
    public InterfazUsuario(){
        try {
            /*colocamos la imagen de fondo*/
            screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            JLabel fondo = new javax.swing.JLabel(cliente.getShortName());
            ImageIcon bg = new javax.swing.ImageIcon(ImageIO.read(getClass().getResource("/imgs/info.jpg")));
            Icon icono = new ImageIcon(bg.getImage().getScaledInstance(screenSize.width, screenSize.height, Image.SCALE_DEFAULT));
            fondo.setIcon(icono);
            //fondo.setIcon(new javax.swing.ImageIcon(ImageIO.read(getClass().getResource("/imgs/info.jpg"))));
            fondo.setHorizontalTextPosition(JLabel.CENTER);
            fondo.setFont(new Font("Serif", Font.PLAIN, 600));
            //JLabel texto = new javax.swing.JLabel("Este es un contenido que se esta agregando desde un jlabel", javax.swing.SwingConstants.CENTER);
            //fondo.add(texto);
            setContentPane(fondo);
            
            
            initComponents();            
            principal=this;
            setLayout(null);
            jep.setEditable(false);
            jep.setEditorKit(kit);
            setIconImage(new ImageIcon(getClass().getResource("/imgs/icono.png")).getImage());
            /*Estilo para los elementos html*/
            StyleSheet styleSheet = kit.getStyleSheet();
            styleSheet.addRule(".producto{color:blue;display:block;}");
            styleSheet.addRule(".tiempo-off{color:red;display:block;font-size:11px}");
            addWindowListener(getWindowAdapter());
            
            String msg = cliente.request("VerificarCierre", "0");
            
            continuarServicio=false;
            if(msg.equals("CierreExitoso")){
                lockScreen();
            }
            else{
                continuarServicio=true;
                IniciarServicio();
            }
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error de conexión", JOptionPane.ERROR_MESSAGE);
            lockScreen();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnIniciar = new javax.swing.JButton();
        detalle = new javax.swing.JPanel();
        responsePane = new javax.swing.JScrollPane();
        jep = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Malo's Ciber 2018");
        setAlwaysOnTop(true);
        setExtendedState(1);
        setFocusCycleRoot(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 117, 39));

        jep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        responsePane.setViewportView(jep);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Total:");

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0");
        total.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout detalleLayout = new javax.swing.GroupLayout(detalle);
        detalle.setLayout(detalleLayout);
        detalleLayout.setHorizontalGroup(
            detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalleLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
            .addComponent(responsePane)
        );
        detalleLayout.setVerticalGroup(
            detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalleLayout.createSequentialGroup()
                .addComponent(responsePane, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));

        btnContinuar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinuarMouseClicked(evt);
            }
        });
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 240, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        if(btnIniciar.getText().equals("Iniciar")){
            if(ping.connect(cliente.getServerIp())){
                try {
                    btnIniciar.setEnabled(false);
                    Thread.sleep(500);
                    IniciarServicio();
                    btnIniciar.setEnabled(true);                    
                } catch (InterruptedException ex) {
                    JOptionPane.showMessageDialog(this,ex.toString(), "Atencion", JOptionPane.ERROR_MESSAGE);
                    //Logger.getLogger(InterfazUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
                JOptionPane.showMessageDialog(this, "No se pudo conectar al servidor, intente nuevamente", "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }
        else{
          //lockScreen();
          //cliente.request("Finalizar",total.getText());
          //dispose(); //habilitar para PC1 para terminar
        }
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void btnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinuarMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnContinuarMouseClicked
    
    void lockScreen(){
        /*Tamaño y posicion del formulario*/
        setVisible(true);
        setExtendedState(MAXIMIZED_BOTH);
        setBounds(0,0,screenSize.width, screenSize.height);
        toFront();
        setResizable(false);
        detalle.setVisible(false);
        btnContinuar.setVisible(false);
        btnIniciar.setVisible(true);
        btnIniciar.setLocation(screenSize.width/2-(btnIniciar.getWidth()/2), screenSize.height/2-(btnIniciar.getHeight()/2));
        btnIniciar.setText("Iniciar");
        btnIniciar.setEnabled(true);        
        usando=false;                
    }
    
    void IniciarServicio(){
        new Thread(){
            @Override
            public void run(){
                try {
                    Thread.sleep(2500);
                    setState(JFrame.ICONIFIED);
                } catch (InterruptedException ex) {
                    Logger.getLogger(InterfazUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
        
        int ancho=445, alto=320;
        setBounds(screenSize.width-ancho, 0, ancho, alto);                        
        jep.setVisible(true);
        detalle.setVisible(true);
        btnContinuar.setVisible(true);
        btnIniciar.setVisible(false);
        //btnIniciar.setLocation(290, 240);
        //btnIniciar.setText("Finalizar");
        if(!continuarServicio){
            String no_venta = cliente.request("Registrar","0"); //registramos la entrada del equipo cliente, total=0
            cliente.agregarDetalleVenta(no_venta); //Registramos como producto: internet
        }
        monitorear();
        usando=true;
        //notificado=false;
        getDetalles();
    }
    
    void getDetalles(){
        jep.setContentType("text/html");
        jep.setText(cliente.requestDetail());
        total.setText(Float.toString(cliente.getTotal()));
        //if(!notificado){
            if(cliente.getTiempoRestante().equals("0 mins")){
                setState(JFrame.NORMAL);
                //JOptionPane.showMessageDialog(null, cliente.getTiempoRestante()+" restantes", "¡Atención!", JOptionPane.WARNING_MESSAGE);
                //notificado=true;
            }
        //}
    }
    
    boolean monitoreando = false;
    void monitorear(){
        if(!monitoreando)
        new Thread(){
            @Override
            public void run(){
                while(usando & !monitoreando){
                    /*System.out.println("ID:"+Thread.currentThread().getId());*/
                    try {
                        monitoreando=true;
                        Thread.sleep(10000);
                        getDetalles();
                        monitoreando=false;
                    } catch (InterruptedException ex) {
                        Logger.getLogger(InterfazUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                //System.out.println("Fin de uso:"+Thread.currentThread().getId());
                continuarServicio=false;
            }
        }.start();
    }        
    
      public WindowAdapter getWindowAdapter() {
        return new WindowAdapter() {
          @Override
          public void windowClosing(WindowEvent we) {
            super.windowClosing(we);
            if(usando){
                setState(JFrame.ICONIFIED);
            }
            else
                javax.swing.JOptionPane.showMessageDialog(principal, "¡Operación no permitida!\n Click en Iniciar para usar el equipo.");
          }
          @Override
          public void windowIconified(WindowEvent we) {             
              if(!usando){
                setState(JFrame.NORMAL);
                javax.swing.JOptionPane.showMessageDialog(principal, "¡De click en el botón iniciar!");                                
              }
          }
        };
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel detalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JEditorPane jep;
    private javax.swing.JScrollPane responsePane;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
